name = "Discord Game SDK Integration"
version = "1.0.0"
author = "Revolution"
description = "Discord integration using Game SDK for rich presence in Roblox Studio"

[datamodel.context]
standalone = ["standalone.luau"]
edit = ["edit.luau"]