<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Runtime\src\RML.Interop\RML.Interop.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Roblox.Tests" />
  </ItemGroup>
</Project>
