#include "rml/dumper/emit/emitter.hpp"

#include "emit/json_emitter.hpp"
#include "emit/mirror_emitter.hpp"
#include "emit/report_emitter.hpp"
#include "emit/shuffle_layout_emitter.hpp"

#include <algorithm>
#include <format>

namespace rml::dumper::emit
{
	void TextEmitter::write_banner(std::ostream& out, const schema::LayoutSet& layouts,
	                               const std::string_view comment)
	{
		out << comment << " Generated by the RobloxModLoader dumper -- do not edit by hand.\n";
		out << comment << " target " << layouts.target << '\n';

		if (!layouts.studio_version.empty())
			out << comment << " studio " << layouts.studio_version << ' ' << layouts.studio_guid << '\n';

		out << '\n';
	}

	std::vector<std::string_view> EmitterRegistry::ids()
	{
		return {"json", "mirror", "report", "shuffle"};
	}

	std::unique_ptr<Emitter> EmitterRegistry::create(const std::string_view id) const
	{
		if (id == "json")
			return std::make_unique<JsonEmitter>();
		if (id == "mirror")
			return std::make_unique<MirrorEmitter>();
		if (id == "report")
			return std::make_unique<ReportEmitter>();
		if (id == "shuffle")
			return std::make_unique<ShuffleLayoutEmitter>();

		return nullptr;
	}

	std::vector<std::unique_ptr<Emitter>> EmitterRegistry::create_all() const
	{
		std::vector<std::unique_ptr<Emitter>> emitters;
		for (const auto id : ids())
			emitters.push_back(create(id));

		return emitters;
	}
}
