#include "dumper/offset_generator.hpp"

#include "dumper/luau_dumper.hpp"

#include <algorithm>
#include <format>
#include <fstream>
#include <optional>
#include <spdlog/spdlog.h>
#include <vector>

namespace dumper
{
	namespace
	{
		std::vector<FieldInfo> get_sorted_fields(const StructInfo& info)
		{
			std::vector<FieldInfo> fields = info.fields;
			std::ranges::sort(fields, [](const FieldInfo& a, const FieldInfo& b) {
				if (a.offset != b.offset)
					return a.offset < b.offset;
				if (a.name != b.name)
					return a.name < b.name;
				return a.type < b.type;
			});
			return fields;
		}

		bool starts_with_common_header(const std::vector<FieldInfo>& fields)
		{
			if (fields.size() < 3)
				return false;

			return fields[0].name == "tt" && fields[0].offset == 0x0 && fields[0].size == 1 && fields[1].name == "marked"
			    && fields[1].offset == 0x1 && fields[1].size == 1 && fields[2].name == "memcat" && fields[2].offset == 0x2
			    && fields[2].size == 1;
		}
	}

	bool OffsetGenerator::generate(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path, OutputFormat format)
	{
		switch (format)
		{
		case OutputFormat::CPP_Header: return generate_cpp_header(structures, output_path);
		case OutputFormat::CPP_Struct: return generate_cpp_structs(structures, output_path);
		case OutputFormat::JSON: return generate_json(structures, output_path);
		case OutputFormat::Genny: return generate_genny(structures, output_path);
		case OutputFormat::LuauShuffle: return generate_luau_shuffle(structures, output_path);
		default: spdlog::error("Unknown output format"); return false;
		}
	}

	bool OffsetGenerator::generate_cpp_structs(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating C++ structs file: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		file << "// Auto-generated by Roblox ModLoader Dumper\n";
		file << "// DO NOT EDIT THIS FILE MANUALLY\n\n";
		file << "#pragma once\n\n";
		file << "#include <cstdint>\n";
		file << "#include <cstddef>\n\n";
		file << "#define COMMON_HEADER \\\n";
		file << "    std::uint8_t tt; \\\n";
		file << "    std::uint8_t marked; \\\n";
		file << "    std::uint8_t memcat\n\n";
		file << "namespace luau {\n\n";

		for (const auto& [struct_name, struct_info] : structures)
		{
			file << "struct " << struct_name << " {\n";

			auto fields = get_sorted_fields(struct_info);

			std::size_t current_offset = 0;
			std::size_t i = 0;

			if (starts_with_common_header(fields))
			{
				file << "    COMMON_HEADER;\n";
				current_offset = 0x4;
				i = 3;
			}

			while (i < fields.size())
			{
				const std::size_t offset = fields[i].offset;
				std::size_t max_size = 0;
				std::size_t j = i;

				while (j < fields.size() && fields[j].offset == offset)
				{
					max_size = std::max(max_size, fields[j].size);
					++j;
				}

				if (offset > current_offset)
				{
					const std::size_t padding_size = offset - current_offset;
					file << "    std::uint8_t padding_" << std::format("{:X}", current_offset) << "[0x" << std::format("{:X}", padding_size) << "];\n";
				}

				if (j - i == 1)
				{
					const auto sanitized = sanitize_name(fields[i].name);
					file << "    " << fields[i].type << " " << sanitized;
					if (sanitized != fields[i].name)
					{
						file << "; // " << fields[i].name << "\n";
					}
					else
					{
						file << ";\n";
					}
				}
				else
				{
					file << "    union {\n";
					for (std::size_t k = i; k < j; ++k)
					{
						const auto sanitized = sanitize_name(fields[k].name);
						file << "        " << fields[k].type << " " << sanitized;
						if (sanitized != fields[k].name)
						{
							file << "; // " << fields[k].name << "\n";
						}
						else
						{
							file << ";\n";
						}
					}
					file << "    };\n";
				}

				current_offset = offset + max_size;
				i = j;
			}

			if (current_offset < struct_info.size)
			{
				const std::size_t padding_size = struct_info.size - current_offset;
				file << "    std::uint8_t padding_final[0x" << std::format("{:X}", padding_size) << "];\n";
			}

			file << "};\n\n";
		}

		file << "} // namespace luau\n\n";
		file.close();

		spdlog::info("C++ structs file generated successfully");
		return true;
	}

	bool OffsetGenerator::generate_cpp_header(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating C++ header file: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		file << "// Auto-generated by Roblox ModLoader Dumper\n";
		file << "// Stable deterministic output for CI diffs\n";
		file << "// DO NOT EDIT THIS FILE MANUALLY\n\n";
		file << "#pragma once\n\n";
		file << "#include <cstdint>\n";
		file << "#include <cstddef>\n\n";
		file << "namespace luau {\n\n";

		for (const auto& [struct_name, struct_info] : structures)
		{
			file << "    // " << struct_name << " (Size: 0x" << std::format("{:X}", struct_info.size) << ")\n";
			file << "    namespace " << sanitize_name(struct_name) << " {\n";

			for (const auto& field : get_sorted_fields(struct_info))
			{
				file << "        constexpr std::size_t " << sanitize_name(field.name) << " = 0x"
				     << std::format("{:X}", field.offset) << "; // " << field.type << "\n";
			}

			file << "        constexpr std::size_t size = 0x" << std::format("{:X}", struct_info.size) << ";\n";
			file << "    }\n\n";
		}

		file << "} // namespace luau\n";
		file.close();

		spdlog::info("C++ header file generated successfully");
		return true;
	}

	bool OffsetGenerator::generate_json(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating JSON file: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		file << "{\n";
		file << "  \"schema_version\": 1,\n";
		file << "  \"generator\": \"roblox_modloader_dumper\",\n";
		file << "  \"deterministic\": true,\n";
		file << "  \"structures\": [\n";

		bool first_struct = true;
		for (const auto& [struct_name, struct_info] : structures)
		{
			if (!first_struct)
				file << ",\n";
			first_struct = false;

			file << "    {\n";
			file << "      \"name\": \"" << struct_name << "\",\n";
			file << "      \"size\": " << struct_info.size << ",\n";
			file << "      \"fields\": [\n";

			const auto fields = get_sorted_fields(struct_info);
			for (std::size_t i = 0; i < fields.size(); ++i)
			{
				const auto& field = fields[i];
				file << "        {\n";
				file << "          \"name\": \"" << field.name << "\",\n";
				file << "          \"offset\": " << field.offset << ",\n";
				file << "          \"size\": " << field.size << ",\n";
				file << "          \"type\": \"" << field.type << "\"\n";
				file << "        }";

				if (i + 1 < fields.size())
					file << ",";

				file << "\n";
			}

			file << "      ]\n";
			file << "    }";
		}

		file << "\n  ]\n";
		file << "}\n";
		file.close();

		spdlog::info("JSON file generated successfully");
		return true;
	}

	bool OffsetGenerator::generate_genny(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating Genny file: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		file << "type uint64_t 8 [[u64]]\n";
		file << "type int64_t 8 [[i64]]\n";
		file << "type int32_t 4 [[i32]]\n";
		file << "type uint32_t 4 [[u32]]\n";
		file << "type int16_t 2 [[i16]]\n";
		file << "type uint16_t 2 [[u16]]\n";
		file << "type uint8_t 1 [[u8]]\n";
		file << "type float 4 [[f32]]\n";
		file << "type char 1\n";
		file << "type void 0\n";
		file << "type bool 1 [[u8]]\n\n";

		for (const auto& [struct_name, struct_info] : structures)
		{
			file << "struct " << struct_name << " {\n";

			std::size_t current_offset = 0;
			for (const auto& field : get_sorted_fields(struct_info))
			{
				if (field.offset > current_offset)
				{
					std::size_t padding_size = field.offset - current_offset;
					file << "    char padding_" << std::format("{:X}", current_offset) << "[0x" << std::format("{:X}", padding_size) << "]\n";
				}

				file << "    " << field.type << " " << field.name << "\n";
				current_offset = field.offset + field.size;
			}

			if (current_offset < struct_info.size)
			{
				std::size_t padding_size = struct_info.size - current_offset;
				file << "    char padding_final[0x" << std::format("{:X}", padding_size) << "]\n";
			}

			file << "}\n\n";
		}

		file.close();

		spdlog::info("Genny file generated successfully");
		return true;
	}

	namespace
	{
		struct ShuffleSpec
		{
			std::string macro_name;
			std::string recovered_key;
			std::string c_type;
			std::vector<std::string> fields;
		};

		const std::vector<ShuffleSpec>& shuffle_specs()
		{
			static const std::vector<ShuffleSpec> specs = {
			    {"lua_State", "lua_State", "lua_State", {"status", "activememcat", "isactive", "singlestep", "top", "base", "global", "ci", "stack_last", "stack", "end_ci", "base_ci", "stacksize", "size_ci", "nCcalls", "baseCcalls", "cachedslot", "gt", "openupval", "gclist", "namecall", "userdata"}},
			    {"CallInfo", "CallInfo", "CallInfo", {"base", "func", "top", "savedpc", "nresults", "flags"}},
			    {"Proto", "Proto", "Proto", {"k", "code", "p", "codeentry", "execdata", "exectarget", "lineinfo", "abslineinfo", "locvars", "upvalues", "source", "debugname", "debuginsn", "typeinfo", "userdata", "gclist", "sizecode", "sizep", "sizelocvars", "sizeupvalues", "sizek", "sizelineinfo", "linegaplog2", "linedefined", "bytecodeid", "sizetypeinfo", "feedbackvec", "feedbackvecsize", "funid"}},
			    {"LuaTable", "Table", "LuaTable", {"tmcache", "readonly", "safeenv", "lsizenode", "nodemask8", "sizearray", "lastfree", "metatable", "array", "node", "gclist"}},
			};
			return specs;
		}

		std::optional<std::size_t> field_offset(const StructInfo& info, const std::string& field)
		{
			for (const auto& f : info.fields)
				if (f.name == field)
					return f.offset;
			return std::nullopt;
		}
	}

	bool OffsetGenerator::generate_luau_shuffle(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating Luau shuffle layout: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		const auto asserts_path = output_path.parent_path() / "luau_shuffle_asserts.h";
		std::ofstream asserts(asserts_path);

		file << "// Auto-generated by the RobloxModLoader dumper -- DO NOT EDIT BY HAND.\n";
		file << "#pragma once\n\n";

		if (asserts)
		{
			asserts << "#pragma once\n\n";
			asserts << "#include <cstddef>\n";
			asserts << "#include \"lstate.h\"\n\n";
		}

		for (const auto& spec : shuffle_specs())
		{
			const std::size_t n = spec.fields.size();

			std::string params;
			for (std::size_t i = 0; i < n; ++i)
				params += (i ? ", a" : "a") + std::to_string(i);

			const auto it = structures.find(spec.recovered_key);

			std::vector<std::size_t> order(n);
			for (std::size_t i = 0; i < n; ++i)
				order[i] = i;

			bool complete = it != structures.end();
			std::vector<std::size_t> offsets(n, 0);
			if (complete)
			{
				for (std::size_t i = 0; i < n && complete; ++i)
				{
					const auto off = field_offset(it->second, spec.fields[i]);
					if (!off)
					{
						complete = false;
						spdlog::warn("{}: field '{}' not recovered -- emitting identity order", spec.macro_name, spec.fields[i]);
						break;
					}
					offsets[i] = *off;
				}
			}

			if (complete)
			{
				std::ranges::stable_sort(order, [&](std::size_t l, std::size_t r) {
					return offsets[l] < offsets[r];
				});
			}

			file << "#define RBX_SHUFFLE_" << spec.macro_name << "(" << params << ") \\\n    ";
			for (std::size_t i = 0; i < n; ++i)
				file << (i ? "; a" : "a") << std::to_string(order[i]);
			file << "\n\n";

			if (asserts && complete)
			{
				for (std::size_t i = 0; i < n; ++i)
					asserts << "static_assert(offsetof(" << spec.c_type << ", " << spec.fields[i] << ") == 0x" << std::format("{:X}", offsets[i]) << ", \"" << spec.c_type << "::" << spec.fields[i] << " layout drift\");\n";
				asserts << "\n";
			}
		}

		file.close();
		if (asserts)
			asserts.close();

		spdlog::info("Luau shuffle layout generated ({} structs)", shuffle_specs().size());
		return true;
	}

	std::string OffsetGenerator::sanitize_name(const std::string& name)
	{
		std::string result = name;

		for (char& c : result)
		{
			if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_')
			{
				c = '_';
			}
		}

		if (!result.empty() && std::isdigit(static_cast<unsigned char>(result[0])))
		{
			result = "_" + result;
		}

		return result;
	}
}
