blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/iRevolutionDev/roblox-modloader/wiki
    about: Check the documentation for guides and API reference
  - name: 💬 Discussions
    url: https://github.com/iRevolutionDev/roblox-modloader/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚨 Security Issues
    url: mailto:security@roblox-modloader.dev
    about: Please report security vulnerabilities privately via email
