using System.Text;

using TypeGenerator.APITypes;

namespace TypeGenerator.Generators;

internal sealed class ClassGenerator(string outputDirectory, ReflectionMetadataReader metadata, ApiDocsReader apiDocs)
{
    private static readonly HashSet<string> _sBaseClasses = new(StringComparer.Ordinal)
    {
        "Object"
    };

    private static readonly HashSet<string> _sKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
        "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
        "using", "virtual", "void", "volatile", "while"
    };

    private readonly SortedSet<string> _danglingBases = new(StringComparer.Ordinal);
    private readonly List<string> _emittedClasses = [];

    private readonly List<string> _renamedMembers = [];

    public void Generate(List<Class> classes)
    {
        if (Directory.Exists(outputDirectory))
        {
            foreach (var stale in Directory.EnumerateFiles(outputDirectory, "*.cs"))
            {
                File.Delete(stale);
            }
        }

        var byName = new Dictionary<string, Class>(StringComparer.Ordinal);
        foreach (Class c in classes.Where(c => !string.IsNullOrEmpty(c.Name)))
        {
            byName[c.Name] = c;
        }

        TypeMapper.SetKnownClasses(byName.Keys);

        foreach (Class c in classes)
        {
            if (string.IsNullOrEmpty(c.Name))
            {
                continue;
            }

            var isBase = _sBaseClasses.Contains(c.Name);

            if (isBase)
            {
                WriteBaseClassPartial(c, byName);
            }
            else
            {
                WriteGeneratedClass(c, byName);
            }
        }

        WriteManifest();
        ReportRenamedMembers();
        ReportDanglingBases();
        ReportUnmappedTypes();
    }

    private static void ReportUnmappedTypes()
    {
        if (TypeMapper.UnmappedTypes.Count == 0)
        {
            return;
        }

        Console.Error.WriteLine(
            $"warning RBXGEN003: {TypeMapper.UnmappedTypes.Count} type(s) have no dedicated C# mapping " +
            "and were emitted as 'object'; the affected members carry no real type safety:");
        foreach (var entry in TypeMapper.UnmappedTypes)
        {
            Console.Error.WriteLine($"warning RBXGEN003:   {entry}");
        }
    }

    private void ReportDanglingBases()
    {
        if (_danglingBases.Count == 0)
        {
            return;
        }

        Console.Error.WriteLine(
            $"warning RBXGEN002: {_danglingBases.Count} class(es) declare a superclass missing from " +
            "the API dump; they were reparented to Instance so the output compiles:");
        foreach (var entry in _danglingBases)
        {
            Console.Error.WriteLine($"warning RBXGEN002:   {entry}");
        }
    }

    private void WriteManifest()
    {
        var generatedDir = Path.GetDirectoryName(outputDirectory) ?? outputDirectory;
        var filePath = Path.Combine(generatedDir, "RobloxClassManifest.g.cs");
        using var sw = new StreamWriter(filePath, false, Encoding.UTF8);

        sw.WriteLine("// <auto-generated/> — DO NOT EDIT MANUALLY.");
        sw.WriteLine("// Maps each Roblox class name to its wrapper type and a handle factory.");
        sw.WriteLine("// Regenerate via Roblox.TypeGenerator to pick up API changes.");
        sw.WriteLine("#nullable enable");
        sw.WriteLine();
        sw.WriteLine("namespace Roblox");
        sw.WriteLine("{");
        sw.WriteLine("    internal static class RobloxClassManifest");
        sw.WriteLine("    {");
        sw.WriteLine("        internal readonly record struct Entry(");
        sw.WriteLine("            string ClassName,");
        sw.WriteLine("            global::System.Type Type,");
        sw.WriteLine("            global::System.Func<nuint, global::Roblox.Object> Factory);");
        sw.WriteLine();
        sw.WriteLine($"        internal static Entry[] All() => new Entry[{_emittedClasses.Count}]");
        sw.WriteLine("        {");

        foreach (var robloxName in _emittedClasses)
        {
            var csName = Utility.ToPascalIdentifier(robloxName);
            var key = robloxName.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sw.WriteLine(
                $"            new(\"{key}\", typeof(global::Roblox.{csName}), " +
                $"static h => global::Roblox.{csName}.FromHandle(h)!),");
        }

        sw.WriteLine("        };");
        sw.WriteLine("    }");
        sw.WriteLine("}");
    }

    private void ReportRenamedMembers()
    {
        if (_renamedMembers.Count == 0)
        {
            return;
        }

        Console.Error.WriteLine(
            $"warning RBXGEN001: {_renamedMembers.Count} member(s) were renamed because their name " +
            "collided with the declaring class name:");
        foreach (var rename in _renamedMembers)
        {
            Console.Error.WriteLine($"warning RBXGEN001:   {rename}");
        }
    }

    private void WriteGeneratedClass(Class c, Dictionary<string, Class> byName)
    {
        var className = Utility.ToPascalIdentifier(c.Name);
        var filePath = Path.Combine(outputDirectory, className + ".cs");
        using var sw = new StreamWriter(filePath, false, Encoding.UTF8);

        var superclass = ResolveSuperclass(c, byName);

        _emittedClasses.Add(c.Name);

        WriteFileHeader(sw);

        ApiDoc? classDoc = apiDocs.GetClass(c.Name);
        var classDescFallback = metadata.ReadClassDesc(c.Name);
        WriteXmlClassDoc(sw, c.Name, classDoc, classDescFallback, 4);

        sw.WriteLine($"    [RobloxClass(\"{c.Name}\")]");

        var hasSubclasses = c.Subclasses is { Count: > 0 };
        var modifier = "public";

        sw.WriteLine($"    {modifier} partial class {className} : {superclass}");
        sw.WriteLine("    {");

        var baseHasFromHandle = EffectiveBaseName(c, byName) is { } pn && pn != "Object";
        WriteConstructorAndFactory(sw, className, c.Name, baseHasFromHandle);

        if (c.Members != null)
        {
            WriteMembers(sw, c, byName, CollectInheritedMemberNames(c, byName));
        }

        sw.WriteLine("    }");
        sw.WriteLine("}");
    }

    private void WriteBaseClassPartial(Class c, Dictionary<string, Class> byName)
    {
        if (c.Members is null || c.Members.Count == 0)
        {
            return;
        }

        var className = Utility.ToPascalIdentifier(c.Name);
        var filePath = Path.Combine(outputDirectory, className + ".Members.cs");
        using var sw = new StreamWriter(filePath, false, Encoding.UTF8);

        sw.WriteLine("#nullable enable");
        sw.WriteLine("// <auto-generated/> — DO NOT EDIT MANUALLY.");
        sw.WriteLine("// This file contains API members auto-generated from the Roblox API dump.");
        sw.WriteLine("// Hand-written members live in src/Roblox/{className}.cs (partial).");
        sw.WriteLine("#pragma warning disable CS8619");
        sw.WriteLine("using System;");
        sw.WriteLine();
        sw.WriteLine("namespace Roblox");
        sw.WriteLine("{");

        ApiDoc? classDoc = apiDocs.GetClass(c.Name);
        var classDescFallback = metadata.ReadClassDesc(c.Name);
        WriteXmlClassDoc(sw, c.Name, classDoc, classDescFallback, 4);

        sw.WriteLine($"    public partial class {className}");
        sw.WriteLine("    {");

        WriteMembers(sw, c, byName, CollectInheritedMemberNames(c, byName));

        sw.WriteLine("    }");
        sw.WriteLine("}");
    }

    private void WriteMembers(StreamWriter sw, Class c, Dictionary<string, Class> byName, ISet<string> inheritedNames)
    {
        foreach ((var csName, MemberBase member, var collided) in SelectMembers(c))
        {
            if (collided)
            {
                _renamedMembers.Add($"{c.Name}.{member.Name} -> {csName}");
            }

            var hides = inheritedNames.Contains(csName);

            switch (member)
            {
                case Property prop:
                    WriteProperty(sw, c, prop, csName, hides);
                    break;

                case Function fn:
                    WriteFunction(sw, c, fn, csName, byName);
                    break;

                case Event evt:
                    WriteEventStub(sw, c, evt, csName, hides);
                    break;

                case Callback cb:
                    WriteCallbackStub(sw, c, cb, csName);
                    break;
            }
        }
    }

    private static List<(string csName, MemberBase member, bool collided)> SelectMembers(Class c)
    {
        var result = new List<(string, MemberBase, bool)>();
        if (c.Members is null)
        {
            return result;
        }

        var winners = new Dictionary<string, MemberBase>(StringComparer.Ordinal);

        foreach (MemberBase member in c.Members)
        {
            if (string.IsNullOrEmpty(member.Name))
            {
                continue;
            }

            var csName = Utility.ToPascalIdentifier(member.Name);

            if (!winners.TryGetValue(csName, out MemberBase? existing))
            {
                winners[csName] = member;
                continue;
            }

            var existingDeprecated = existing.IsDeprecated;
            var memberDeprecated = member.IsDeprecated;
            if (existingDeprecated && !memberDeprecated)
            {
                winners[csName] = member;
                continue;
            }

            if (memberDeprecated && !existingDeprecated)
            {
                continue;
            }

            var existingPascal = char.IsUpper(existing.Name![0]);
            var memberPascal = !string.IsNullOrEmpty(member.Name) && char.IsUpper(member.Name[0]);
            if (!existingPascal && memberPascal)
            {
                winners[csName] = member;
            }
        }

        foreach ((var rawCsName, MemberBase member) in winners)
        {
            var collidesWithClassName = rawCsName == c.Name;
            var csName = collidesWithClassName
                ? member switch
                {
                    Property => rawCsName + "Value",
                    Function => rawCsName + "Func",
                    Event => rawCsName + "Event",
                    Callback => rawCsName + "Callback",
                    _ => rawCsName + "Member"
                }
                : rawCsName;

            result.Add((csName, member, collidesWithClassName));
        }

        return result;
    }

    private static ISet<string> CollectInheritedMemberNames(Class c, Dictionary<string, Class> byName)
    {
        var inherited = new HashSet<string>(StringComparer.Ordinal);
        var parent = EffectiveBaseName(c, byName);
        while (parent is not null && byName.TryGetValue(parent, out Class? parentClass))
        {
            foreach (var (csName, _, _) in SelectMembers(parentClass))
            {
                inherited.Add(csName);
            }

            parent = EffectiveBaseName(parentClass, byName);
        }

        return inherited;
    }

    private static void WriteObsolete(StreamWriter sw, Class c, MemberBase member)
    {
        if (!member.IsDeprecated)
        {
            return;
        }

        var name = member.Name?.Replace("\"", "\\\"");
        sw.WriteLine($"        [global::System.Obsolete(\"'{c.Name}.{name}' is deprecated.\")]");
    }

    private void WriteProperty(StreamWriter sw, Class c, Property prop, string memberName, bool hides)
    {
        ApiDoc? memberDoc = apiDocs.GetMember(c.Name, prop.Name ?? string.Empty);
        var descFallback = metadata.ReadMemberDesc(c.Name, prop.Name ?? string.Empty);
        var access = PropertyAccess.Resolve(prop);
        var readOnly = access.IsReadOnly;
        var writeOnly = access.IsWriteOnly;
        var csType = TypeMapper.ToCSharp(prop.ValueType);
        var newKw = hides ? "new " : string.Empty;


        var bang = csType.EndsWith('?') ? string.Empty : "!";
        var propName = prop.Name?.Replace("\"", "\\\"");

        WriteXmlMemberDoc(sw, c.Name, prop.Name ?? string.Empty, memberDoc, descFallback,
            null, null,
            IsUsableDefault(prop.Default) ? prop.Default : null, 8);
        WriteObsolete(sw, c, prop);

        if (readOnly)
        {
            sw.WriteLine($"        public {newKw}{csType} {memberName}");
            sw.WriteLine("        {");
            sw.WriteLine(
                $"            get => global::Roblox.Reflection.GetProperty<{csType}>(this, \"{propName}\"){bang};");
            sw.WriteLine("        }");
        }
        else if (writeOnly)
        {
            sw.WriteLine($"        public {newKw}{csType} {memberName}");
            sw.WriteLine("        {");
            sw.WriteLine(
                $"            set => global::Roblox.Reflection.SetProperty<{csType}>(this, \"{propName}\", value);");
            sw.WriteLine("        }");
        }
        else
        {
            sw.WriteLine($"        public {newKw}{csType} {memberName}");
            sw.WriteLine("        {");
            sw.WriteLine(
                $"            get => global::Roblox.Reflection.GetProperty<{csType}>(this, \"{propName}\"){bang};");
            sw.WriteLine(
                $"            set => global::Roblox.Reflection.SetProperty<{csType}>(this, \"{propName}\", value);");
            sw.WriteLine("        }");
        }

        sw.WriteLine();
    }

    private void WriteFunction(
        StreamWriter sw,
        Class c,
        Function fn,
        string memberName,
        Dictionary<string, Class> byName)
    {
        ApiDoc? memberDoc = apiDocs.GetMember(c.Name, fn.Name ?? string.Empty);
        var descFallback = metadata.ReadMemberDesc(c.Name, fn.Name ?? string.Empty);
        var returnType = TypeMapper.ReturnType(fn.ReturnType);
        List<(string CsType, string Name, bool Optional)> resolved = ResolveParameters(fn.Parameters);
        var @params = BuildParameterList(fn.Parameters);
        var args = BuildArgumentList(fn.Parameters);
        var isVoid = TypeMapper.IsVoid(returnType);

        var isYield = fn.Tags?.Contains("Yields", StringComparer.Ordinal) == true;

        if (isYield)
        {
            var awaited = isVoid ? "object?[]" : returnType;

            WriteXmlMemberDoc(sw, c.Name, fn.Name ?? string.Empty, memberDoc, descFallback,
                fn.Parameters, $"Task<{awaited}>", null, 8,
                resolvedParams: resolved.Select(p => (p.Name, p.CsType)).ToList());

            WriteObsolete(sw, c, fn);

            sw.WriteLine($"        public global::System.Threading.Tasks.Task<{awaited}> {memberName}({@params})");
            sw.WriteLine(
                $"            => global::Roblox.Reflection.InvokeAsync<{awaited}>(this, \"{fn.Name}\"{args});");
            sw.WriteLine();
            return;
        }

        WriteXmlMemberDoc(sw, c.Name, fn.Name ?? string.Empty, memberDoc, descFallback,
            fn.Parameters, isVoid ? null : returnType, null, 8,
            resolvedParams: resolved.Select(p => (p.Name, p.CsType)).ToList());

        WriteObsolete(sw, c, fn);

        var bang = isVoid || returnType.EndsWith('?') ? string.Empty : "!";
        var callExpr = isVoid
            ? $"global::Roblox.Reflection.Invoke<object?>(this, \"{fn.Name}\"{args})"
            : $"global::Roblox.Reflection.Invoke<{returnType}>(this, \"{fn.Name}\"{args}){bang}";

        if (isVoid)
        {
            sw.WriteLine($"        public void {memberName}({@params})");
            sw.WriteLine($"            => {callExpr};");
        }
        else
        {
            sw.WriteLine($"        public {returnType} {memberName}({@params})");
            sw.WriteLine($"            => {callExpr};");
        }

        sw.WriteLine();
    }


    private void WriteEventStub(StreamWriter sw, Class c, Event evt, string memberName, bool hides)
    {
        ApiDoc? memberDoc = apiDocs.GetMember(c.Name, evt.Name ?? string.Empty);
        var descFallback = metadata.ReadMemberDesc(c.Name, evt.Name ?? string.Empty);
        List<(string CsType, string Name, bool Optional)> resolved = ResolveParameters(evt.Parameters);
        WriteXmlMemberDoc(sw, c.Name, evt.Name ?? string.Empty, memberDoc, descFallback,
            evt.Parameters, null, null, 8,
            resolvedParams: resolved.Select(p => (p.Name, p.CsType)).ToList());

        var delegateType = resolved.Count == 0
            ? "Action"
            : $"Action<{string.Join(", ", resolved.Select(p => p.CsType))}>";
        var newKw = hides ? "new " : string.Empty;

        WriteObsolete(sw, c, evt);
        sw.WriteLine($"        public {newKw}event {delegateType}? {memberName}");
        sw.WriteLine("        {");
        sw.WriteLine($"            add {{ if (value is not null) AddEventHandler(\"{evt.Name}\", value); }}");
        sw.WriteLine($"            remove {{ if (value is not null) RemoveEventHandler(\"{evt.Name}\", value); }}");
        sw.WriteLine("        }");
        sw.WriteLine();
    }

    private void WriteCallbackStub(StreamWriter sw, Class c, Callback cb, string memberName)
    {
        ApiDoc? memberDoc = apiDocs.GetMember(c.Name, cb.Name ?? string.Empty);
        var descFallback = metadata.ReadMemberDesc(c.Name, cb.Name ?? string.Empty);
        WriteXmlMemberDoc(sw, c.Name, cb.Name ?? string.Empty, memberDoc, descFallback,
            null, null, null, 8,
            "Callback binding is not yet implemented in the native layer.");
        sw.WriteLine($"        // public Func<object?>? {memberName}; // TODO: native callback binding");
        sw.WriteLine();
    }

    private static void WriteConstructorAndFactory(StreamWriter sw, string className, string robloxName,
        bool baseHasFromHandle)
    {
        var newKw = baseHasFromHandle ? "new " : string.Empty;
        sw.WriteLine(
            "        /// <summary>Wraps an existing native Roblox instance identified by <paramref name=\"handle\"/>.</summary>");
        sw.WriteLine(
            $"        /// <param name=\"handle\">Native pointer to the underlying Roblox {robloxName}.</param>");
        sw.WriteLine(
            "        /// <exception cref=\"ArgumentException\">Thrown when <paramref name=\"handle\"/> is zero.</exception>");
        sw.WriteLine($"        internal {className}(nuint handle) : base(handle) {{ }}");
        sw.WriteLine();
        sw.WriteLine($"        internal {className}(string className) : base(className) {{ }}");
        sw.WriteLine();
        sw.WriteLine("        /// <summary>");
        sw.WriteLine($"        /// Creates a <see cref=\"{className}\"/> wrapper from a native handle, or returns");
        sw.WriteLine("        /// <see langword=\"null\"/> when <paramref name=\"handle\"/> is zero.");
        sw.WriteLine("        /// </summary>");
        sw.WriteLine($"        public static {newKw}{className}? FromHandle(nuint handle)");
        sw.WriteLine($"            => handle == 0 ? null : new {className}(handle);");
        sw.WriteLine();
        sw.WriteLine("        /// <summary>");
        sw.WriteLine(
            $"        /// Creates a new <see cref=\"{className}\"/> instance with the default Roblox class name.");
        sw.WriteLine("        /// </summary>");
        sw.WriteLine($"        public {className}() : base(RobloxTypeRegistry.ClassNameOf<{className}>()) {{ }}");
        sw.WriteLine();
        sw.WriteLine();
    }

    private static void WriteFileHeader(StreamWriter sw)
    {
        sw.WriteLine("#nullable enable");
        sw.WriteLine("// <auto-generated/> — DO NOT EDIT MANUALLY.");
        sw.WriteLine("// Generated by Roblox.TypeGenerator from the Roblox API dump.");
        sw.WriteLine("// Re-run the generator tool to pick up API changes.");
        sw.WriteLine("#pragma warning disable CS8619");
        sw.WriteLine("using System;");
        sw.WriteLine();
        sw.WriteLine("namespace Roblox");
        sw.WriteLine("{");
    }

    private static void WriteXmlClassDoc(
        StreamWriter sw,
        string className,
        ApiDoc? apiDoc,
        string? fallbackDesc,
        int indent)
    {
        var pad = new string(' ', indent);
        var summary = ApiDocsReader.HtmlToXmlDoc(apiDoc?.Documentation) ?? EscapeXml(fallbackDesc ?? string.Empty);

        if (string.IsNullOrEmpty(summary) && apiDoc == null)
        {
            return;
        }

        sw.WriteLine($"{pad}/// <summary>");
        if (!string.IsNullOrEmpty(summary))
        {
            sw.WriteLine($"{pad}/// {summary}");
        }
        else
        {
            sw.WriteLine($"{pad}/// Roblox <c>{EscapeXml(className)}</c> class.");
        }

        sw.WriteLine($"{pad}/// </summary>");

        if (!string.IsNullOrEmpty(apiDoc?.LearnMoreLink))
        {
            sw.WriteLine($"{pad}/// <seealso href=\"{apiDoc!.LearnMoreLink}\"/>");
        }
    }

    private static void WriteXmlMemberDoc(
        StreamWriter sw,
        string className,
        string memberName,
        ApiDoc? apiDoc,
        string? fallbackDesc,
        List<Parameter>? parameters,
        string? returnCsType,
        string? defaultValue,
        int indent,
        string? extraNote = null,
        IReadOnlyList<(string Name, string CsType)>? resolvedParams = null)
    {
        var pad = new string(' ', indent);
        var summary = ApiDocsReader.HtmlToXmlDoc(apiDoc?.Documentation) ?? EscapeXml(fallbackDesc ?? string.Empty);

        var hasContent = !string.IsNullOrEmpty(summary)
                         || parameters?.Count > 0
                         || !string.IsNullOrEmpty(returnCsType)
                         || !string.IsNullOrEmpty(defaultValue)
                         || !string.IsNullOrEmpty(extraNote)
                         || !string.IsNullOrEmpty(apiDoc?.LearnMoreLink);

        if (!hasContent)
        {
            return;
        }

        sw.WriteLine($"{pad}/// <summary>");
        if (!string.IsNullOrEmpty(summary))
        {
            sw.WriteLine($"{pad}/// {summary}");
        }
        else
        {
            sw.WriteLine($"{pad}/// <c>{EscapeXml(className)}.{EscapeXml(memberName)}</c>");
        }

        if (!string.IsNullOrEmpty(defaultValue))
        {
            sw.WriteLine($"{pad}/// <para><b>Default:</b> <c>{EscapeXml(defaultValue)}</c></para>");
        }

        if (!string.IsNullOrEmpty(extraNote))
        {
            sw.WriteLine($"{pad}/// <para><b>Note:</b> {EscapeXml(extraNote)}</para>");
        }

        sw.WriteLine($"{pad}/// </summary>");

        if (resolvedParams != null)
        {
            foreach (var (pName, pCsType) in resolvedParams)
            {
                sw.WriteLine($"{pad}/// <param name=\"{pName}\">A <c>{EscapeXml(pCsType)}</c> value.</param>");
            }
        }
        else if (parameters != null)
        {
            foreach (Parameter p in parameters)
            {
                var pName = LowerFirst(Utility.ToPascalIdentifier(p.Name ?? "arg"));
                var pType = EscapeXml(TypeMapper.ToCSharp(p.Type));
                sw.WriteLine($"{pad}/// <param name=\"{pName}\">A <c>{pType}</c> value.</param>");
            }
        }

        if (!string.IsNullOrEmpty(returnCsType) && !TypeMapper.IsVoid(returnCsType))
        {
            sw.WriteLine(
                $"{pad}/// <returns>A <c>{EscapeXml(returnCsType)}</c> value returned by the engine.</returns>");
        }

        if (!string.IsNullOrEmpty(apiDoc?.LearnMoreLink))
        {
            sw.WriteLine($"{pad}/// <seealso href=\"{apiDoc!.LearnMoreLink}\"/>");
        }
    }

    private static List<(string CsType, string Name, bool Optional)> ResolveParameters(List<Parameter>? parameters)
    {
        if (parameters is null || parameters.Count == 0)
        {
            return [];
        }

        // Unique names are assigned front-to-back for deterministic numbering.
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var names = parameters
            .Select(p => EnsureUnique(LowerFirst(Utility.ToPascalIdentifier(p.Name ?? "arg")), usedNames))
            .ToArray();

        var slots = new (string CsType, string Name, bool Optional)[parameters.Count];
        var requiredSeen = false;

        for (var i = parameters.Count - 1; i >= 0; i--)
        {
            var baseType = TypeMapper.ToCSharp(parameters[i].Type);
            var typeNullable = baseType.EndsWith('?');
            var hasDefault = !string.IsNullOrEmpty(parameters[i].Default);

            if (!requiredSeen && (typeNullable || hasDefault))
            {
                slots[i] = (TypeMapper.MakeNullable(baseType), names[i], true);
            }
            else
            {
                requiredSeen = true;
                slots[i] = (baseType, names[i], false);
            }
        }

        return [.. slots];
    }

    private static string BuildParameterList(List<Parameter>? parameters)
        => string.Join(", ", ResolveParameters(parameters)
            .Select(p => $"{p.CsType} {p.Name}{(p.Optional ? " = null" : string.Empty)}"));

    private static string BuildArgumentList(List<Parameter>? parameters)
    {
        List<(string CsType, string Name, bool Optional)> resolved = ResolveParameters(parameters);
        return resolved.Count == 0
            ? string.Empty
            : ", " + string.Join(", ", resolved.Select(p => p.Name));
    }

    private string ResolveSuperclass(Class c, Dictionary<string, Class> byName)
    {
        var baseName = EffectiveBaseName(c, byName);

        if (baseName is null or "Object")
        {
            return "global::Roblox.Object";
        }

        if (!byName.ContainsKey(c.Superclass ?? string.Empty) && c.Superclass != "<<<Object>>>")
        {
            _danglingBases.Add($"{c.Name} : {c.Superclass} -> Instance");
        }

        return Utility.ToPascalIdentifier(baseName);
    }

    private static string? EffectiveBaseName(Class c, Dictionary<string, Class> byName)
    {
        var s = c.Superclass;
        if (string.IsNullOrEmpty(s))
        {
            return null;
        }

        if (s == "<<<Object>>>")
        {
            return "Object";
        }

        if (s.StartsWith("<<<", StringComparison.Ordinal))
        {
            return null;
        }

        return byName.ContainsKey(s) ? s : "Instance";
    }

    private static bool IsUsableDefault(string? value)
        => !string.IsNullOrEmpty(value)
           && !value.StartsWith("__api_dump_", StringComparison.Ordinal);

    private static string EscapeXml(string? s)
    {
        if (s is null)
        {
            return string.Empty;
        }

        return s.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");
    }

    private static string LowerFirst(string s)
    {
        if (string.IsNullOrEmpty(s))
        {
            return s;
        }

        return char.ToLowerInvariant(s[0]) + s[1..];
    }

    private static string EnsureUnique(string name, HashSet<string> used)
    {
        if (_sKeywords.Contains(name))
        {
            name = "@" + name;
        }

        if (used.Add(name))
        {
            return name;
        }

        var i = 2;
        string candidate;
        do
        {
            candidate = name + i++;
        } while (!used.Add(candidate));

        return candidate;
    }
}