message("Luau")

set(LUAU_BUILD_CLI OFF CACHE BOOL "Build Luau CLI" FORCE)
set(LUAU_BUILD_TESTS OFF CACHE BOOL "Build Luau tests" FORCE)
set(LUAU_BUILD_WEB OFF CACHE BOOL "Build Luau web components" FORCE)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/luau)

if (TARGET Luau.VM)
    target_include_directories(Luau.VM PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
endif ()
if (TARGET Luau.Compiler)
    target_include_directories(Luau.Compiler PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
endif ()
if (TARGET Luau.Analysis)
    target_include_directories(Luau.Analysis PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
endif ()
if (TARGET Luau.CodeGen)
    target_include_directories(Luau.CodeGen PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
endif ()
if (TARGET Luau.Ast)
    target_include_directories(Luau.Ast PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
endif ()