#include "dumper/offset_generator.hpp"

#include "dumper/luau_dumper.hpp"

#include <algorithm>
#include <chrono>
#include <format>
#include <fstream>
#include <spdlog/spdlog.h>
#include <vector>

namespace dumper
{

	bool OffsetGenerator::generate(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path, OutputFormat format)
	{
		switch (format)
		{
		case OutputFormat::CPP_Header: return generate_cpp_header(structures, output_path);
		case OutputFormat::CPP_Struct: return generate_cpp_structs(structures, output_path);
		case OutputFormat::JSON: return generate_json(structures, output_path);
		case OutputFormat::Genny: return generate_genny(structures, output_path);
		default: spdlog::error("Unknown output format"); return false;
		}
	}

	bool OffsetGenerator::generate_cpp_structs(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating C++ structs file: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		const auto now  = std::chrono::system_clock::now();
		const auto time = std::chrono::system_clock::to_time_t(now);

		file << "// Auto-generated by Roblox ModLoader Dumper\n";
		file << "// Generated at: " << std::ctime(&time);
		file << "// DO NOT EDIT THIS FILE MANUALLY\n\n";
		file << "#pragma once\n\n";
		file << "#include <cstdint>\n";
		file << "#include <cstddef>\n\n";
		file << "namespace luau {\n\n";

		for (const auto& [struct_name, struct_info] : structures)
		{
			file << "struct " << struct_name << " {\n";

			std::vector<FieldInfo> fields = struct_info.fields;
			std::ranges::sort(fields, [](const FieldInfo& a, const FieldInfo& b) {
				if (a.offset != b.offset)
					return a.offset < b.offset;
				return a.name < b.name;
			});

			std::size_t current_offset = 0;
			for (std::size_t i = 0; i < fields.size();)
			{
				const std::size_t offset = fields[i].offset;
				std::size_t max_size     = 0;
				std::size_t j            = i;

				while (j < fields.size() && fields[j].offset == offset)
				{
					max_size = std::max(max_size, fields[j].size);
					++j;
				}

				if (offset > current_offset)
				{
					const std::size_t padding_size = offset - current_offset;
					file << "    std::uint8_t padding_" << std::format("{:X}", current_offset) << "[0x" << std::format("{:X}", padding_size) << "];\n";
				}

				if (j - i == 1)
				{
					const auto sanitized = sanitize_name(fields[i].name);
					file << "    " << fields[i].type << " " << sanitized;
					if (sanitized != fields[i].name)
					{
						file << "; // " << fields[i].name << "\n";
					}
					else
					{
						file << ";\n";
					}
				}
				else
				{
					file << "    union {\n";
					for (std::size_t k = i; k < j; ++k)
					{
						const auto sanitized = sanitize_name(fields[k].name);
						file << "        " << fields[k].type << " " << sanitized;
						if (sanitized != fields[k].name)
						{
							file << "; // " << fields[k].name << "\n";
						}
						else
						{
							file << ";\n";
						}
					}
					file << "    };\n";
				}

				current_offset = offset + max_size;
				i              = j;
			}

			if (current_offset < struct_info.size)
			{
				const std::size_t padding_size = struct_info.size - current_offset;
				file << "    std::uint8_t padding_final[0x" << std::format("{:X}", padding_size) << "];\n";
			}

			file << "};\n\n";
		}

		file << "} // namespace luau\n";
		file.close();

		spdlog::info("C++ structs file generated successfully");
		return true;
	}

	bool OffsetGenerator::generate_cpp_header(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating C++ header file: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		const auto now  = std::chrono::system_clock::now();
		const auto time = std::chrono::system_clock::to_time_t(now);

		file << "// Auto-generated by Roblox ModLoader Dumper\n";
		file << "// Generated at: " << std::ctime(&time);
		file << "// DO NOT EDIT THIS FILE MANUALLY\n\n";
		file << "#pragma once\n\n";
		file << "#include <cstdint>\n";
		file << "#include <cstddef>\n\n";
		file << "namespace luau {\n\n";

		for (const auto& [struct_name, struct_info] : structures)
		{
			file << "    // " << struct_name << " (Size: 0x" << std::format("{:X}", struct_info.size) << ")\n";
			file << "    namespace " << sanitize_name(struct_name) << " {\n";

			for (const auto& field : struct_info.fields)
			{
				file << "        constexpr std::size_t " << sanitize_name(field.name) << " = 0x"
				     << std::format("{:X}", field.offset) << "; // " << field.type << "\n";
			}

			file << "        constexpr std::size_t size = 0x" << std::format("{:X}", struct_info.size) << ";\n";
			file << "    }\n\n";
		}

		file << "} // namespace luau\n";
		file.close();

		spdlog::info("C++ header file generated successfully");
		return true;
	}

	bool OffsetGenerator::generate_json(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating JSON file: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		file << "{\n";
		file << R"(  "generated_at": ")" << std::chrono::system_clock::now() << "\",\n";
		file << "  \"structures\": {\n";

		bool first_struct = true;
		for (const auto& [struct_name, struct_info] : structures)
		{
			if (!first_struct)
				file << ",\n";
			first_struct = false;

			file << "    \"" << struct_name << "\": {\n";
			file << "      \"size\": " << struct_info.size << ",\n";
			file << "      \"fields\": {\n";

			bool first_field = true;
			for (const auto& [name, offset, size, type] : struct_info.fields)
			{
				if (!first_field)
					file << ",\n";
				first_field = false;

				file << "        \"" << name << "\": {\n";
				file << "          \"offset\": " << offset << ",\n";
				file << "          \"size\": " << size << ",\n";
				file << R"(          "type": ")" << type << "\"\n";
				file << "        }";
			}

			file << "\n      }\n";
			file << "    }";
		}

		file << "\n  }\n";
		file << "}\n";
		file.close();

		spdlog::info("JSON file generated successfully");
		return true;
	}

	bool OffsetGenerator::generate_genny(const std::map<std::string, StructInfo>& structures, const std::filesystem::path& output_path)
	{
		spdlog::info("Generating Genny file: {}", output_path.string());

		std::ofstream file(output_path);
		if (!file.is_open())
		{
			spdlog::error("Failed to open file for writing: {}", output_path.string());
			return false;
		}

		file << "type uint64_t 8 [[u64]]\n";
		file << "type int64_t 8 [[i64]]\n";
		file << "type int32_t 4 [[i32]]\n";
		file << "type uint32_t 4 [[u32]]\n";
		file << "type int16_t 2 [[i16]]\n";
		file << "type uint16_t 2 [[u16]]\n";
		file << "type uint8_t 1 [[u8]]\n";
		file << "type float 4 [[f32]]\n";
		file << "type char 1\n";
		file << "type void 0\n";
		file << "type bool 1 [[u8]]\n\n";

		for (const auto& [struct_name, struct_info] : structures)
		{
			file << "struct " << struct_name << " {\n";

			std::size_t current_offset = 0;
			for (const auto& field : struct_info.fields)
			{
				if (field.offset > current_offset)
				{
					std::size_t padding_size = field.offset - current_offset;
					file << "    char padding_" << std::format("{:X}", current_offset) << "[0x" << std::format("{:X}", padding_size) << "]\n";
				}

				file << "    " << field.type << " " << field.name << "\n";
				current_offset = field.offset + field.size;
			}

			if (current_offset < struct_info.size)
			{
				std::size_t padding_size = struct_info.size - current_offset;
				file << "    char padding_final[0x" << std::format("{:X}", padding_size) << "]\n";
			}

			file << "}\n\n";
		}

		file.close();

		spdlog::info("Genny file generated successfully");
		return true;
	}

	std::string OffsetGenerator::sanitize_name(const std::string& name)
	{
		std::string result = name;

		for (char& c : result)
		{
			if (!std::isalnum(c) && c != '_')
			{
				c = '_';
			}
		}

		if (!result.empty() && std::isdigit(result[0]))
		{
			result = "_" + result;
		}

		return result;
	}
}
