message("Luau")

set(LUAU_BUILD_CLI OFF CACHE BOOL "Build Luau CLI" FORCE)
set(LUAU_BUILD_TESTS OFF CACHE BOOL "Build Luau tests" FORCE)
set(LUAU_BUILD_WEB OFF CACHE BOOL "Build Luau web components" FORCE)

add_subdirectory(${LUAU_SOURCE_DIR})

if (TARGET Luau.VM)
    target_include_directories(Luau.VM PRIVATE "${LUAU_SOURCE_DIR}/include" "${ROBLOX_MODLOADER_ROOT_DIR}/${ROBLOX_MODLOADER_INCLUDE_DIR}")
endif ()
if (TARGET Luau.Compiler)
    target_include_directories(Luau.Compiler PRIVATE "${LUAU_SOURCE_DIR}/include" "${ROBLOX_MODLOADER_ROOT_DIR}/${ROBLOX_MODLOADER_INCLUDE_DIR}")
endif ()
if (TARGET Luau.Analysis)
    target_include_directories(Luau.Analysis PRIVATE "${LUAU_SOURCE_DIR}/include" "${ROBLOX_MODLOADER_ROOT_DIR}/${ROBLOX_MODLOADER_INCLUDE_DIR}")
endif ()
if (TARGET Luau.CodeGen)
    target_include_directories(Luau.CodeGen PRIVATE "${LUAU_SOURCE_DIR}/include" "${ROBLOX_MODLOADER_ROOT_DIR}/${ROBLOX_MODLOADER_INCLUDE_DIR}")
endif ()
if (TARGET Luau.Ast)
    target_include_directories(Luau.Ast PRIVATE "${LUAU_SOURCE_DIR}/include" "${ROBLOX_MODLOADER_ROOT_DIR}/${ROBLOX_MODLOADER_INCLUDE_DIR}")
endif ()