include(cmake/CPM.cmake)

set(RML_SPDLOG_OPTIONS
    "SPDLOG_BUILD_SHARED OFF"
    "SPDLOG_BUILD_EXAMPLE OFF"
    "SPDLOG_BUILD_TESTS OFF"
    "SPDLOG_INSTALL OFF"
)

if (NOT RML_PLATFORM_WINDOWS)
    list(APPEND RML_SPDLOG_OPTIONS "SPDLOG_USE_STD_FORMAT ON")
endif ()

CPMAddPackage(
    NAME spdlog
    VERSION 1.15.0
    GITHUB_REPOSITORY gabime/spdlog
    OPTIONS ${RML_SPDLOG_OPTIONS}
)